language: go
go_import_path: github.com/ovcharovvladimir/Prysm
sudo: false
matrix:
  include:
    - os: linux
      go: 1.10.x
      env:
        - lint
      before_install:
      -go get -u github.com/alecthomas/gometalinter
      script:
        - gometalinter --install && gometalinter ./... --deadline=10m --exclude=client/internal/client_helper.go

    - language: node_js
      os: linux
      env:
        - solidity
      node_js:
        - "lts/*"
      before_install:
        - npm install -g solium
      install: false # Skip npm install.
      script:
        # Check solidity linter.
        - solium -d contracts/
