kind: Service
apiVersion: v1
metadata:
  name: gess-bootnode
spec:
  selector:
    component: bootnode
    universe: gess
  ports:
    - port: 8545
      targetPort: 8545
      name: rpc
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-udp
      protocol: UDP
    - port: 30301
      targetPort: 30301
      name: bootnode-udp
      protocol: UDP