kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: gess-ethstats
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ethstats
      universe: gess
  template:
    metadata:
      labels:
        component: ethstats
        universe: gess
    spec:
      priorityClassName: production-priority
      containers:
        - name: ethstats
          image: ethereumex/eth-netstats:latest
          command: ["npm"]
          args: ["start"]
          ports: 
            - containerPort: 3000
              name: web
          env:
            - name: WS_SECRET
              valueFrom:
                secretKeyRef:
                  name: ethstats-secrets
                  key: ws
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
